const imgList = [
  {
    type: "S/S",
    img: "./images/p1.jpg",
    title: "Title-1",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Incidunt distinctio",
  },
  {
    type: "F/W",
    img: "./images/p2.jpg",
    title: "Title-2",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Incidunt distinctio",
  },
  {
    type: "S/S",
    img: "./images/p3.jpg",
    title: "Title-3",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Incidunt distinctio",
  },
  {
    type: "F/W",
    img: "./images/p4.jpg",
    title: "Title-4",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Incidunt distinctio",
  },
  {
    type: "S/S",
    img: "./images/p5.jpg",
    title: "Title-5",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Incidunt distinctio",
  },
  {
    type: "F/W",
    img: "./images/p6.jpg",
    title: "Title-6",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Incidunt distinctio",
  },
  {
    type: "S/S",
    img: "./images/p7.jpg",
    title: "Title-7",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Incidunt distinctio",
  },
  {
    type: "F/W",
    img: "./images/p8.jpg",
    title: "Title-8",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Incidunt distinctio",
  },
  {
    type: "S/S",
    img: "./images/p9.jpg",
    title: "Title-9",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Incidunt distinctio",
  },
  {
    type: "F/W",
    img: "./images/p10.jpg",
    title: "Title-10",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Incidunt distinctio",
  },
  {
    type: "S/S",
    img: "./images/p11.jpg",
    title: "Title-11",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Incidunt distinctio",
  },
  {
    type: "F/W",
    img: "./images/p12.jpg",
    title: "Title-12",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Incidunt distinctio",
  },
  {
    type: "S/S",
    img: "./images/p13.jpg",
    title: "Title-13",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Incidunt distinctio",
  },
  {
    type: "F/W",
    img: "./images/p14.jpg",
    title: "Title-14",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Incidunt distinctio",
  },
  {
    type: "S/S",
    img: "./images/p15.jpg",
    title: "Title-15",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Incidunt distinctio",
  },
]
